library(reticulate)
getwd()
#py_version()
#use_python_version("3.10")
#py_version()
#r_var<-10
#r_to_py(r_var)
#source_python("pyrun.py",envir = parent.frame())
#test_r<-100
#sample_text<-readLines("sample.txt")
qtemp<-tempfile("test.xml")
qfile<-"yudale003.txt"
#writeLines(sample_text,qfile)
#tempfile_py<-tempfile("sample.xml")
#source_python("test.py",envir = globalenv())
#source_python("parser.mod.py",envir = globalenv())
source_python("parser.mod.py")
#source_python("parser.local.src.py")
writeLines(parser$tree_to_write,qtemp)
library(xml2)
tei<-read_xml(qtemp)
#qres<-readLines(qfile)
#qfile
#source_python("parser.local.py")
#source_python("parser.py")

#parser$process_file("yudale003.txt")
#py_eval("parser.process_file('yudale003.txt')")
#py_eval("Parser()")
#Parser$process_file("sample.txt")
#py_install("lxml")
#py_install("html5")
#py_install("bs4")
#py_install("transliterate")
#py_install("pkg_resources")
#install_python("3.12")
#use_python_version("3.10")
#py_version()
#py_version()
#py_config()
