library(reticulate)
getwd()
test_r<-100
source_python("test.py",envir = globalenv())
source_python("parser.mod.py")
source_python("parser.py")

parser$process_file("sample.txt")
Parser$process_file("sample.txt")
#py_install("lxml")
#py_install("html5")
#py_install("bs4")
install_python("3.12")
use_python_version("3.12")
py_version()
